### PR TITLE
Base image changes

### PR DESCRIPTION
**Pull request by mikn**
- RBAC support
 - Master as a stateful set and backing PV
 - Resource low limit defaults
 - Tighter privileges (no privileged containers for Elasticsearch, just init)
 - Dedicated heap size config
 - Changed default service type for client service to ClusterIP for security
 - Added in a NOTES.txt
 - Removed data service, as there should be no need to expose it to the cluster
 - Enable readinessProbe for the statefulsets
 - No more kibana
 - Allow for custom configuration in elasticsearch.yml

### CODE REVIEW

**Comment by clockworksoul** [comment]
Hi @mikn!

Very nice work! If you decide to contribute back to the clockworksoul/helm-elasticsearch project, I would be very grateful. :)

Best,

Matt (aka ClockworkSoul)

**Comment by mikn** [comment]
@clockworksoul Thank you, Matt! Very nice to hear! At this point however, it is almost a complete rewrite. If you still agree to all changes, I wouldn't mind merging it back to you. I have another couple coming in soon.
I was however thinking that I could get it into the official charts repository as well. What are your thoughts on that?
There is still at least one feature that I've left out from the official charts repository so far, like the scaling back script.

**Comment by clockworksoul** [comment]
There's a fair amount of work by a number of authors going on over at https://github.com/clockworksoul/helm-elasticsearch and we'd sure be happy for the help! A lot of your changes would be very welcome, and as they say: many hands make light work. :)

I'd like to see the chart accepted into the official charts. There may be some complications there though, seeing that there's already an Elasticsearch chart in the official incubator charts. Working together though, we might be able to convince them though!

**Comment by mikn** [comment]
Is there anything that you specifically would not want to include right now out of the changes here? :)
I'm working on a kibana helm chart as well to replace removal of Kibana from your chart.

**Comment by clockworksoul** [comment]
Absolutely yes. The first thing I really want is a better accounting of things that our chart is missing (I hate to call it mine: it has my name but it’s really a community effort). I added a couple of issues over at https://github.com/clockworksoul/helm-elasticsearch/issues but it’s still woefully incomplete, and if you have a few minutes to brain dump there, I’d be super grateful. 

Aside from that, I’d be thrilled for literally anything you can add that would help us achieve functional parity or superiority with the official incubator chart, with a particular emphasis on features that are missing from the pires charts because they would be difficult to implement or wouldn’t be useful for a general audience. 

So many thanks!!

Regarding Kibana: that wasn’t removed from my chart, but it is optional by setting a values flag. Do you mean you removed it from your fork?

-Matt

**Comment by mikn** [comment]
@clockworksoul Yes, I removed it from this fork. I was thinking that the easiest way would be for me to open a giant PR just merging this repo into yours, but I can also cherry-pick the features one by one and offer my advice for yours if that's preferable.
I will in the meantime pursue making this chart a strict superset of the official elasticsearch chart and check the maintainers' interest in getting the added features in. Particularly switching cluster discovery mechanism and getting plugins installed as an init container.

**Comment by clockworksoul** [comment]
> Yes, I removed it from this fork. 

Ah, gotcha. I understand now.

> I was thinking that the easiest way would be for me to open a giant PR just merging this repo into yours, but I can also cherry-pick the features one by one and offer my advice for yours if that's preferable.

I know it's a pain, but I far prefer the latter option since it makes reviews easier and lets us make focused suggestions on the individual incoming features.

Thank you again for your help! I'm very grateful!

**Pull request merged**
